### ISSUE TITLE
The ripper does not rip the last segment

### ISSUE THREAD

**Issue by HAmamiya** [Xavier-Lam/r18-ripper#1]
Can't provide detailed steps to reproduce the issue for obvious reason.

If the last "chunk" (segment) is media_b6000000_3658.ts as listed in the playlist file, the ripper only rip up to segment 3567. 

If argument is "-s 3658:3658" the ripper output an empty file. If arguments is "-s 3657:3658", only one segment is in the output file. If no slice defined, full video except the last segment is written to output file.

**Comment by Xavier-Lam** [comment]
I will commit a new version this weekend, simply edit [line 139](https://github.com/Xavier-Lam/r18-ripper/blob/d1c6c9a925caf287b05d931b488183b4a9987b0b/r18ripper.py#L139), change variable `end` from `-1` to `None` can solve the problem.

**Comment by Xavier-Lam** [comment]
Or you can try using "-s 0:3658", this may solve the problem too.

**Comment by HAmamiya** [comment]
Thanks! Of couse the first method (change -1 to none) is more favouriable.
Cheers!

**Comment by HAmamiya** [comment]
> I will commit a new version this weekend, simply edit [line 139](https://github.com/Xavier-Lam/r18-ripper/blob/d1c6c9a925caf287b05d931b488183b4a9987b0b/r18ripper.py#L139), change variable `end` from `-1` to `None` can solve the problem.

Well, this does not fix the issue when `-s` with last segment number as end is set. Last segment number+1 is requied to download the last segment.
