### ISSUE TITLE
m3u8url error -SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by KenzoM** [Xavier-Lam/r18-ripper#2]
I am not sure where to get the `m3u8url` from the Network tab when I play the r18's R player.

I getting the error `SyntaxError: invalid syntax` when I try to run:

`r18-ripper <m3u8url> -o file.ts`

**Comment by HAmamiya** [comment]
I do not use R player app so not sure if you are referring the the R player that required to be installed in OS. This script rips the stream from online, not decrypting the files nor injecting the R player.

**Comment by Xavier-Lam** [comment]
I have never used R player, this ripper is only compatible for browser player, you can see [this](https://github.com/Riven-Spell/r18-ripper) to learn how to get a m3u8url.

**Comment by Xavier-Lam** [comment]
1. Open the development tools(F12) in your browser
2. Choose Network panel
3. Choose Fetch/XHR
4. Open the video player page (a url likes https://www.r18.com/player?cid=mide00070)
5. The first request captured named with a prefix 'playlist.m3u8' with status 200 is what you needed.
![image](https://user-images.githubusercontent.com/8982940/192129309-5ff5aad2-b84d-435c-bf3c-d0649f8906c6.png)

If you are still getting Syntax Error, please check if you are using python 3, I used a keyword only argument feature which is not supported in python 2.

**Comment by KenzoM** [comment]
Got it -- it looks like I was using python2 and upgrading to python3 made it work. Thanks!
