### ISSUE TITLE
How to capture the m3u8 request

### ISSUE THREAD

**Issue by KiraJYQiu** [Xavier-Lam/r18-ripper#3]
Can I just ask a stupid question about how to capture the m3u8 request? 
I have tried out many ways and didn’t get the m3u8 address. I have used the source sniffer to get many links of ts files but links didn’t work on the ripper.

**Comment by Xavier-Lam** [comment]
You can see [this](https://github.com/Riven-Spell/r18-ripper) to learn how to get a m3u8url.

**Comment by Xavier-Lam** [comment]
1. Open the development tools(F12) in your browser
2. Choose Network panel
3. Choose Fetch/XHR
4. Open the video player page (a url likes https://www.r18.com/player?cid=mide00070)
5. The first request captured named with a prefix 'playlist.m3u8' with status 200 is what you needed.
![image](https://user-images.githubusercontent.com/8982940/192129309-5ff5aad2-b84d-435c-bf3c-d0649f8906c6.png)

**Comment by KiraJYQiu** [comment]
![2022-09-25 15-21-55](https://user-images.githubusercontent.com/81470698/192129623-6596688e-9109-4763-94be-c55135b7b953.png)
I don't see the playlist

**Comment by Xavier-Lam** [comment]
Did you open the page before you opened the development tools? If so, you need to refresh the page. And choose the fourth request starts with "chunklist_b400" might also work, but this would only be able to download the 4M bitrate one.
